feat: fail on high+ findings (#4)
* feat: fail on high+ findings

* fix md formatting

diff --git a/.github/workflows/security-scan.yml b/.github/workflows/security-scan.yml
--- a/.github/workflows/security-scan.yml
+++ b/.github/workflows/security-scan.yml
@@ -37,7 +37,10 @@ jobs:
     - name: Install Python dependencies
       run: python -m pip install --upgrade pip pandas tabulate
     - name: Deduplication and OWASP mapping
-      run: python scanner/scan.py && echo "{markdown content}" >> $GITHUB_STEP_SUMMARY
+      id: parse
+      run: |
+        HIGH_SEVERITY_FINDINGS=$(python scanner/scan.py)
+        echo "HIGH_SEVERITY_FINDINGS=$HIGH_SEVERITY_FINDINGS">> $GITHUB_OUTPUT
     - name: Upload Security Report
       uses: actions/upload-artifact@v7
       with:
@@ -45,4 +48,7 @@ jobs:
         path: security_report.md
     - name: Display Report in Summary
       run: cat security_report.md >> "$GITHUB_STEP_SUMMARY"
+    - name: Fail if Critical or High Severity Findings
+      if: steps.parse.outputs.HIGH_SEVERITY_FINDINGS == 'True'
+      run: echo "⚠️  Job failed due to non-zero number of Critical or High severity security findings. See job summary for details." && exit 1
         
